name: "Build fava Docker image"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'beancount/fava/**'
      - '.github/workflows/fava-docker-build.yml'
  schedule:
    - cron: '30 22 * * 5' # See https://crontab.guru/#0_3_*_*_*

env:
  REPOSITORY_NAME: ${{ github.repository }}
  GHCR_IMAGE_NAME: ghcr.io/y0ngb1n/fava
  DOCKERHUB_IMAGE_NAME: y0ngb1n/fava

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'y0ngb1n/dockerized'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Fetch fava version
        id: get_fava_version
        run: |
          export TZ='Asia/Shanghai'
          echo "build_date=$(date '+%Y-%m-%d-%H-%M-%S')" >> $GITHUB_OUTPUT
          local_version=v`sed -nr 's/fava==(.*)/\1/p' beancount/fava/requirements.txt`
          latest_version=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/beancount/fava/tags | jq -r '.[0].name')
          if [ "$local_version" != "$latest_version" ]; then
            echo "fava_version=$latest_version" >> $GITHUB_OUTPUT
            echo "fava_latest_version=$latest_version" >> $GITHUB_ENV
            echo "fava_pip_version=$(echo $latest_version | sed 's/v//g')" >> $GITHUB_ENV
          fi
      - name: Update fava version
        if: steps.get_fava_version.outputs.fava_version != ''
        run: |
          sed -i 's/fava==.*/fava=='"$fava_pip_version"'/g' beancount/fava/requirements.txt
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        if: steps.get_fava_version.outputs.fava_version != ''
        with:
          context: beancount/fava
          file: ./beancount/fava/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ${{ env.GHCR_IMAGE_NAME }}:${{ steps.get_fava_version.outputs.fava_version }}
            ${{ env.GHCR_IMAGE_NAME }}:latest
            ${{ env.DOCKERHUB_IMAGE_NAME }}:${{ steps.get_fava_version.outputs.fava_version }}
            ${{ env.DOCKERHUB_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Commit changes
        if: steps.get_fava_version.outputs.fava_version != ''
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A

          arr[0]="😂"
          arr[1]="😱"
          arr[2]="👿"
          arr[3]="💩"
          arr[4]="🙏"
          arr[5]="🙈"
          arr[6]="🐐"
          arr[7]="🤖"
          arr[8]="🪿"
          arr[9]="👻"

          rand=$[$RANDOM % ${#arr[@]}]

          git commit -m "chore(bot): ${arr[$rand]} update fava version to ${{ steps.get_fava_version.outputs.fava_version }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        # uses: actions-js/push@master
        if: steps.get_fava_version.outputs.fava_version != ''
        with:
          directory: "beancount/fava"
          github_token: ${{ secrets.GITHUB_TOKEN }}
